import { Grid } from '@mui/material'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/Components/UI/Header/Header'
import { BG_COLOUR } from '@/utils/colours'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Grid container bgcolor={BG_COLOUR} >

      <Header />

      {children}
    </Grid>
  )
}
